#!/bin/bash
DOTENV=./app/.env

if test -f "$DOTENV"; then
    echo 'Building your Duda Instant Site Demo'
    cd app/ &&
    npm install &&
    npm run build &&
    cd ../frontend &&
    npm install &&
    npm run build &&
    cd .. &&
    echo 'Build successful. Try ./deploy' &&
    exit 1    
else
    echo "Your .env is missing. Try running ./configure first."
    exit 0
fi